package com.mk.jsongen.model.stock;

import java.util.List;

public class StockLastName {

    public static final List<String> LAST_NAMES = List.of(
            "Cathcart",
            "Portier",
            "Kealey",
            "Drapeau",
            "Vanostrand",
            "Samsel",
            "Roeser",
            "Priestley",
            "Lofgren",
            "Desir",
            "Brungardt",
            "Sosa",
            "Joe",
            "Byam",
            "Bakley",
            "Meacham",
            "Allmond",
            "Gadberry",
            "Stillings",
            "Yelvington",
            "Tom",
            "Bungard",
            "Velasco",
            "Younker",
            "Richmond",
            "Vanvliet",
            "Devault",
            "Mitts",
            "Soucie",
            "Trojacek",
            "Tillman",
            "Bettes",
            "Calvo",
            "Embrey",
            "Betton",
            "Scherer",
            "Farfan",
            "Bouie",
            "Clymer",
            "Joslin",
            "Remick",
            "Ordway",
            "Freed",
            "Condon",
            "Sproul",
            "Doucet",
            "Batista",
            "Perkinson",
            "Wooten",
            "Galiano");
}
