package com.mk.jsongen.model.stock;

import java.util.List;

public class StockFirstName {

    public static final List<String> FIRST_NAMES = List.of(
            "Tressa",
            "Christel",
            "Colby",
            "Mac",
            "Alfreda",
            "Jeromy",
            "Voncile",
            "Ola",
            "Adina",
            "Sybil",
            "Shaunta",
            "Yee",
            "Kimber",
            "Aliza",
            "Rachelle",
            "Rivka",
            "Jerry",
            "Erica",
            "Angla",
            "Claud",
            "Cornell",
            "Tomiko",
            "Lakeshia",
            "Leone",
            "Lorna",
            "Henry",
            "Bonnie",
            "Selene",
            "Lazaro",
            "Garland",
            "Barton",
            "Margarite",
            "Destiny",
            "Porfirio",
            "Jarrod",
            "Terresa",
            "Justine",
            "Carlyn",
            "Concha",
            "Rebecca",
            "Suzann",
            "Kathleen",
            "Jamika",
            "Latoya",
            "Janine",
            "Bobbie",
            "Kerry",
            "Gus",
            "Shan",
            "Jerrod");
}
